name: CD build and push docker image     #name of the CD wf

on: 
    push:
        branches: 
            - main

jobs:       #build and push docker image
  docker-build-check:      #name of the jobs action
    runs-on: ubuntu-latest   #run it on fresh linux machine
    steps:
        #check the code out 
      - name: Checkout code   #name of the steps action
        uses: actions/checkout@v4   #this download my code into a temporary linux machine

        #log in to dockerhub
      - name: Log in to dockerhub
        uses: docker/login-action@v4   #pre-built docker log in uses
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        #build and push image 
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:                   #steps need to build image 
            context: cicd/task-1/app
            push: true 
            tags: abdijalilimam/flask-app:latest # this is so that it pull the latest images 