name: first docker build check wf #name of the wf

on: [push] #the trigger

jobs: #the list of jobs this wf will do
  docker-build-check:      #name of the jobs action
    runs-on: ubuntu-latest   #run it on fresh linux machine
    steps:
      - name: Checkout code   #name of the steps action
        uses: actions/checkout@v4   #this download my code into a temporary linux machine
      - name: Docker build check     #name of the build action
        run: docker build -t flask-app ./cicd/task-1/app  #the path where the action is taking place 
